<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel Extend\Warranty\ViewModel\Installation */
$viewModel = $block->getData('viewModel');
if ($viewModel) {
    $viewModel->prepareBlockData();
}
?>
<?php if (isset($viewModel) && $viewModel->getExtendEnable()) : ?>
    <script src="<?= $viewModel->getJsMode() ?>"></script>

    <script>
        Extend.config(<?= $viewModel->getJsonConfig() ?>);
    </script>
<?php endif; ?>

<script>
    var BASE_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
