<?php

/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var Extend\Warranty\ViewModel\Installation $viewModel
 */
$viewModel = $block->getData('viewModel');

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <hr>
            <?php if (isset($viewModel) && $viewModel->getExtendEnable()) : ?>
                <div id="extend-offer"></div>

                <script type="text/x-magento-init">
                {
                    "#extend-offer": {
                        "extendWarranties":{"productSku":"<?= $_product->getTypeId() == 'configurable' ? '' : $_product->getSku() ?>"}
                    }
                }
                </script>
            <?php endif; ?>

            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>