<?php
/**
 * Created by PhpStorm.
 * User: lazaro
 * Date: 19/12/18
 * Time: 04:09 PM
 */

/** @var $block Extend\Warranty\Block\System\Config\Products\Button
 */
?>
<div class="extend-sync-button-container">
    <button id="syncBtn" data-mage-init='{"productSync": {"url": "<?= $block->getUrl('extend/products/sync') ?>"}}'>
        <span>Sync Products</span>
    </button>
    <div class="sync-info">
        <p id="sync-msg"><strong><?=__('Last Sync:').' '?></strong><span id="sync-time"><?= !empty($block->getLastSync()) ? $block->getLastSync() : 'Never'?></span></p>
        <a id="cancel_sync">Cancel Sync</a>
    </div>
</div>