<?php
/** @var $viewModel Extend\Warranty\ViewModel\Installation
 */
$viewModel = $block->getData('viewModel');
if ($viewModel) {
    $viewModel->prepareBlockData();
}
?>
<?php if (isset($viewModel) && $viewModel->getExtendEnable()) : ?>
    <?php if ($viewModel->getExtendLive()) : ?>
        <script src="https://sdk.helloextend.com/extend-sdk-client/v1/extend-sdk-client.min.js"></script>
    <?php else: ?>
        <script src="https://sdk.helloextend.com/extend-sdk-client/v1/demo/extend-sdk-client.min.js"></script>
    <?php endif; ?>

    <script>
        Extend.config({ storeId: '<?= $block->escapeHtmlAttr($block->escapeUrl($viewModel->getExtendStoreId())); ?>' });
    </script>
<?php endif; ?>

<script>
    var BASE_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
</script>
