<?php

/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var Extend\Catalog\ViewModel\Warranty $viewModel
 */
$viewModel = $block->getViewModel();

$warranties = $viewModel->getWarranties($block->getProduct()->getSku());
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <hr>
            <?php if ($viewModel->isExtendEnabled()): ?>
                <h2>Fast and free replacement if your product breaks</h2>
                <p>Protect your purchase with EXTEND.</p>
                <fieldset>

                    <?php
                    /**
                     * @var \Magento\Catalog\Model\Product $warranty
                     */
                    foreach ($warranties as $warranty):
                        ?>
                        <div>
                            <input class="warranty" type="checkbox" id="<?= $warranty->getSku() ?>">
                            <label class="checkboxLabel"
                                   for="<?= $warranty->getSku() ?>"><?= $warranty->getCustomAttribute('warranty_length')->getValue() ?>
                                years - <strong>$<?= $warranty->getPrice() ?></strong></label>
                        </div>
                    <?php endforeach; ?>
                </fieldset>
                <hr>
            <?php endif; ?>

            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function ($) {

        $(".warranty").change(function () {
            $(".warranty").not(this).prop('checked', false);
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }






</script>