<?php

/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var Extend\Warranty\ViewModel\Installation $viewModel
 */
$viewModel = $block->getData('viewModel');

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <hr>
            <?php if (isset($viewModel) && $viewModel->getExtendEnable()) : ?>
                <div id="extend-offer"></div>

                <script type="text/javascript">
                    require(['jquery', 'underscore'], function ($, _) {

                        Extend.buttons.render('#extend-offer', {
                            referenceId: '<?= $_product->getTypeId() == 'simple' ? $_product->getSku() : '' ?>'
                        });

                        $(document).ready(function () {
                            $('div.product-options-wrapper').click(() => {
                                selectedProduct();
                            });
                        });

                        function match(attributes, selected_options) {
                            return _.isEqual(attributes, selected_options);
                        }

                        function selectedProduct() {
                            let selected_options = {};

                            let options = $('div.swatch-attribute');

                            options.each((index, value) => {
                                let attribute_id = $(value).attr('attribute-id');
                                let option_selected = $(value).attr('option-selected');
                                if (!attribute_id || !option_selected) {
                                    return;
                                }
                                selected_options[attribute_id] = option_selected;
                            });

                            const productConfig = $('[data-role=swatch-options]').data('mageSwatchRenderer').options.jsonConfig;

                            for (let [productId, attributes] of Object.entries(productConfig.index)) {
                                if (match(attributes, selected_options)) {
                                    let sku = productConfig.skus[productId];

                                    const component = Extend.buttons.instance('#extend-offer');
                                    component.setActiveProduct(sku);
                                }
                            }
                        }
                    });
                </script>
            <?php endif; ?>

            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script>
    require([
        'jquery'
    ], function ($) {

        $(".warranty").change(function () {
            $(".warranty").not(this).prop('checked', false);
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }



















</script>