<?php  $html = <<<EOD
<table>
    <tbody>
        <tr>
           <td>
                <img id="extend-logo" src="https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/xgp5hobvl2kqp50r9bum">
            </td>
            <td>
                <p>Extend generates new revenue for your store, increases overall purchase 
                conversions, and provides customers with streamlined product protection and peace of mind.</p>
                <p><a>Learn more</a></p>
            </td>
            <td>
            
            </td>
        </tr>
    </tbody>
</table>
<hr>
EOD;
?>


<?= $html ?>
