<?php  $html = <<<EOD
<table>
    <tbody>
        <tr>
           <td>
                <img id="extend-logo" src="{$this->getViewFileUrl('Extend_Warranty::images/Extend_logo_slogan.svg')}" alt="Logo Image">
            </td>
            <td>
                <p id="extend-intro">Extend generates new revenue for your store, increases overall purchase 
                conversions, and provides customers with streamlined product protection and peace of mind.</p>
                <p><a>Learn more</a></p>
            </td>
            <td>
                <img id="extend-mobile" src="{$this->getViewFileUrl('Extend_Warranty::images/mobile-offer.svg')}" alt="Mobile Image">
            </td>
        </tr>
    </tbody>
</table>
<hr>
EOD;
?>


<?= $html ?>
