<?php
/**
 * Created by PhpStorm.
 * User: lazaro
 * Date: 19/12/18
 * Time: 04:09 PM
 */

/** @var $block Extend\Warranty\Block\System\Config\Products\Button
 */
?>
<div class="extend-sync-button-container">
    <table class="extend-sync">
        <tr>
            <td width="40%" id="eSync">
                <button id="syncBtn" class="" data-mage-init='{"productSync": {"url": "<?= $block->getUrl('extend/products/sync') ?>"}}'><span>Sync Products</span></button>
            </td>
            <td width="60%" id="eSync">
                <p id="sync-msg" class=""><strong><?=__('Last Sync:').' '?></strong><span id="sync-time"><?= !empty($block->getLastSync()) ? $block->getLastSync() : 'Never'?></span></p>
                <a id="cancel_sync" style="color: red; display: none" href="javascript:void(0)"><strong>Cancel Sync</strong></a>
            </td>
        </tr>
    </table>
</div>